# Generated by Django 3.1.5 on 2021-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyPrice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_2011_2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_index', models.CharField(max_length=20, verbose_name='省份编号')),
                ('province_name', models.CharField(max_length=20, verbose_name='省份')),
                ('vegetable_index', models.CharField(max_length=20, verbose_name='蔬菜类型编号')),
                ('vegetable_name', models.CharField(max_length=20, verbose_name='蔬菜类型')),
                ('craft_index', models.CharField(max_length=20, verbose_name='蔬菜编号')),
                ('craft_name', models.CharField(max_length=20, verbose_name='蔬菜名称')),
                ('c_unit', models.CharField(max_length=20, verbose_name='单位')),
                ('market_index', models.CharField(max_length=20, verbose_name='市场编号')),
                ('market_name', models.CharField(max_length=80, verbose_name='市场名称')),
                ('price_2011', models.CharField(max_length=200, verbose_name='2011年数据')),
                ('price_2012', models.CharField(max_length=200, verbose_name='2012年数据')),
                ('price_2013', models.CharField(max_length=200, verbose_name='2013年数据')),
                ('price_2014', models.CharField(max_length=200, verbose_name='2014年数据')),
                ('price_2015', models.CharField(max_length=200, verbose_name='2015年数据')),
                ('price_2016', models.CharField(max_length=200, verbose_name='2016年数据')),
                ('price_2017', models.CharField(max_length=200, verbose_name='2017年数据')),
                ('price_2018', models.CharField(max_length=200, verbose_name='2018年数据')),
                ('price_2019', models.CharField(max_length=200, verbose_name='2019年数据')),
                ('price_2020', models.CharField(max_length=200, verbose_name='2020年数据')),
            ],
            options={
                'verbose_name': '2011-2020价格数据',
                'verbose_name_plural': '2011-2020价格数据',
                'db_table': 'price_2011_2020',
            },
        ),
    ]
