# Generated by Django 2.2.2 on 2020-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('qq', models.CharField(max_length=20, verbose_name='QQ')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'users',
            },
        ),
    ]
